// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531170942_AddFKConnections")]
    partial class AddFKConnections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Appointment.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("fecha_cita");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fin");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("ReceptionistId")
                        .HasColumnType("uuid")
                        .HasColumnName("recepcionista_id");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_servicio_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("idx_cita_fecha");

                    b.HasIndex("ReceptionistId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("idx_cita_vehiculo");

                    b.ToTable("cita", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Audit.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("json")
                        .HasColumnName("datos_anteriores");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("json")
                        .HasColumnName("datos_nuevos");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entidad");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_origen");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_accion");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("idx_audit_fecha");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_audit_usuario");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Citys.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ciudad", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_pais_codigo");

                    b.ToTable("pais", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CustomerAddresses.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("ciudad_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<bool>("Primary")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CustomerId");

                    b.ToTable("cliente_direccion", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CustomerEmails.CustomerEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<bool>("Primary")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("cliente_correo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CustomerPhones.CustomerPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("PhoneType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("cliente_telefono", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("num_documento");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_documento");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Surnames")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_cliente_num_documento");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Departments.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("pais_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("departamento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.InventoryLog.InventoryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("orden_id");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("compra_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("SparePartId")
                        .HasColumnType("uuid")
                        .HasColumnName("repuesto_id");

                    b.Property<int>("StockResultante")
                        .HasColumnType("integer")
                        .HasColumnName("stock_resultante");

                    b.Property<string>("TypeMovement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_movimiento");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("idx_log_fecha");

                    b.HasIndex("OrderId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("SparePartId")
                        .HasDatabaseName("idx_log_repuesto");

                    b.HasIndex("UserId");

                    b.ToTable("log_inventario", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Invoice.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostoRepuestos")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("costo_repuestos");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("descuento");

                    b.Property<decimal>("ImpuestoPct")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("impuesto_pct");

                    b.Property<decimal>("ManoDeObra")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("mano_de_obra");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("orden_id");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_fact_id");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("uq_factura_orden");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("factura", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.InvoiceStatus.InvoiceStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_estado_factura_nombre");

                    b.ToTable("estado_factura", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MechanicTask.MechanicTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<decimal>("HourlyCost")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costo_hora");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("horas_trabajadas");

                    b.Property<Guid>("MechanicId")
                        .HasColumnType("uuid")
                        .HasColumnName("mecanico_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("orden_id");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_servicio_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<Guid?>("mecanico_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("orden_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("tipo_servicio_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MechanicId")
                        .HasDatabaseName("idx_tarea_mecanico");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_tarea_orden");

                    b.HasIndex("mecanico_id");

                    b.HasIndex("orden_id");

                    b.HasIndex("tipo_servicio_id");

                    b.ToTable("tarea_mecanico", null, t =>
                        {
                            t.Property("mecanico_id")
                                .HasColumnName("mecanico_id1");

                            t.Property("orden_id")
                                .HasColumnName("orden_id1");

                            t.Property("tipo_servicio_id")
                                .HasColumnName("tipo_servicio_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.MileageHistory.MileageHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("integer")
                        .HasColumnName("kilometraje");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fuente");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehiculo_id");

                    b.Property<Guid?>("vehiculo_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("idx_hkm_vehiculo");

                    b.HasIndex("vehiculo_id");

                    b.ToTable("historial_kilometraje", null, t =>
                        {
                            t.Property("vehiculo_id")
                                .HasColumnName("vehiculo_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderDetail.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("orden_id");

                    b.Property<decimal>("PriceSnapshot")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_snapshot");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("SparePartId")
                        .HasColumnType("uuid")
                        .HasColumnName("repuesto_id");

                    b.Property<Guid?>("orden_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("repuesto_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_do_orden");

                    b.HasIndex("orden_id");

                    b.HasIndex("repuesto_id");

                    b.HasIndex("OrderId", "SparePartId")
                        .IsUnique()
                        .HasDatabaseName("uq_do_orden_repuesto");

                    b.ToTable("detalle_orden", null, t =>
                        {
                            t.Property("orden_id")
                                .HasColumnName("orden_id1");

                            t.Property("repuesto_id")
                                .HasColumnName("repuesto_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderMechanic.OrderMechanic", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("orden_id");

                    b.Property<Guid>("MechanicId")
                        .HasColumnType("uuid")
                        .HasColumnName("mecanico_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaAsignacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_asignacion");

                    b.Property<Guid?>("mecanico_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("orden_id")
                        .HasColumnType("uuid");

                    b.HasKey("OrderId", "MechanicId");

                    b.HasIndex("mecanico_id");

                    b.HasIndex("orden_id");

                    b.ToTable("orden_mecanico", null, t =>
                        {
                            t.Property("mecanico_id")
                                .HasColumnName("mecanico_id1");

                            t.Property("orden_id")
                                .HasColumnName("orden_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderNote.OrderNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaNota")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nota");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("orden_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid?>("orden_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("usuario_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("orden_id");

                    b.HasIndex("usuario_id");

                    b.ToTable("nota_orden", null, t =>
                        {
                            t.Property("orden_id")
                                .HasColumnName("orden_id1");

                            t.Property("usuario_id")
                                .HasColumnName("usuario_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderService.OrderService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("cita_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaEntregaReal")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega_real");

                    b.Property<DateOnly?>("FechaEstimada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_estimada");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<int>("KilometrajeIngreso")
                        .HasColumnType("integer")
                        .HasColumnName("kilometraje_ingreso");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("ReceptionistId")
                        .HasColumnType("uuid")
                        .HasColumnName("recepcionista_id");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehiculo_id");

                    b.Property<Guid?>("estado_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("recepcionista_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("vehiculo_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("idx_orden_estado");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("idx_orden_vehiculo");

                    b.HasIndex("estado_id");

                    b.HasIndex("recepcionista_id");

                    b.HasIndex("vehiculo_id");

                    b.ToTable("orden_servicio", null, t =>
                        {
                            t.Property("estado_id")
                                .HasColumnName("estado_id1");

                            t.Property("recepcionista_id")
                                .HasColumnName("recepcionista_id1");

                            t.Property("vehiculo_id")
                                .HasColumnName("vehiculo_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderServiceType.OrderServiceType", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("orden_id");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_servicio_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("orden_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("tipo_servicio_id")
                        .HasColumnType("uuid");

                    b.HasKey("OrderId", "ServiceTypeId");

                    b.HasIndex("orden_id");

                    b.HasIndex("tipo_servicio_id");

                    b.ToTable("orden_tipo_servicio", null, t =>
                        {
                            t.Property("orden_id")
                                .HasColumnName("orden_id1");

                            t.Property("tipo_servicio_id")
                                .HasColumnName("tipo_servicio_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderStatus.OrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_estado_orden_nombre");

                    b.ToTable("estado_orden", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrderStatusHistory.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("orden_id");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid?>("estado_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("orden_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("usuario_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_heo_orden");

                    b.HasIndex("estado_id");

                    b.HasIndex("orden_id");

                    b.HasIndex("usuario_id");

                    b.ToTable("historial_estado_orden", null, t =>
                        {
                            t.Property("estado_id")
                                .HasColumnName("estado_id1");

                            t.Property("orden_id")
                                .HasColumnName("orden_id1");

                            t.Property("usuario_id")
                                .HasColumnName("usuario_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Payment.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("factura_id");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("metodo_pago_id");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("idx_pago_factura");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("pago", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PaymentMethod.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_metodo_pago_nombre");

                    b.ToTable("metodo_pago", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Purchase.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("fecha_compra");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid?>("proveedor_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("usuario_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("proveedor_id");

                    b.HasIndex("usuario_id");

                    b.ToTable("compra", null, t =>
                        {
                            t.Property("proveedor_id")
                                .HasColumnName("proveedor_id1");

                            t.Property("usuario_id")
                                .HasColumnName("usuario_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.PurchaseDetail.PurchaseDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("compra_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("SparePartId")
                        .HasColumnType("uuid")
                        .HasColumnName("repuesto_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<Guid?>("compra_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("repuesto_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("compra_id");

                    b.HasIndex("repuesto_id");

                    b.HasIndex("PurchaseId", "SparePartId")
                        .IsUnique()
                        .HasDatabaseName("uq_dc_compra_repuesto");

                    b.ToTable("detalle_compra", null, t =>
                        {
                            t.Property("compra_id")
                                .HasColumnName("compra_id1");

                            t.Property("repuesto_id")
                                .HasColumnName("repuesto_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_rol_nombre");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ServiceType.ServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("EstimatedDays")
                        .HasColumnType("integer")
                        .HasColumnName("dias_estimados");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_tipo_servicio_nombre");

                    b.ToTable("tipo_servicio", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SpareCategory.SpareCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_categoria_repuesto_nombre");

                    b.ToTable("categoria_repuesto", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SparePart.SparePart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer")
                        .HasColumnName("stock_actual");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("stock_minimo");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_id");

                    b.Property<Guid?>("categoria_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("unidad_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("categoria_id");

                    b.HasIndex("unidad_id");

                    b.ToTable("repuesto", null, t =>
                        {
                            t.Property("categoria_id")
                                .HasColumnName("categoria_id1");

                            t.Property("unidad_id")
                                .HasColumnName("unidad_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.SparePartSupplier.SparePartSupplier", b =>
                {
                    b.Property<Guid>("SparePartId")
                        .HasColumnType("uuid")
                        .HasColumnName("repuesto_id");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_compra");

                    b.Property<Guid?>("proveedor_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("repuesto_id")
                        .HasColumnType("uuid");

                    b.HasKey("SparePartId", "SupplierId");

                    b.HasIndex("proveedor_id");

                    b.HasIndex("repuesto_id");

                    b.ToTable("repuesto_proveedor", null, t =>
                        {
                            t.Property("proveedor_id")
                                .HasColumnName("proveedor_id1");

                            t.Property("repuesto_id")
                                .HasColumnName("repuesto_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Supplier.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("ciudad_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Nit")
                        .IsUnique()
                        .HasDatabaseName("uq_proveedor_nit");

                    b.ToTable("proveedor", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UnitMeasure.UnitMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("abreviatura");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("unidad_medida", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<string>("Surnames")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<Guid?>("rol_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.HasIndex("rol_id");

                    b.ToTable("usuario", null, t =>
                        {
                            t.Property("rol_id")
                                .HasColumnName("rol_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Vehicle.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("modelo_id");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("vin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ModelId");

                    b.HasIndex("Plate")
                        .IsUnique()
                        .HasDatabaseName("uq_vehiculo_placa");

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasDatabaseName("uq_vehiculo_vin");

                    b.ToTable("vehiculo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VehicleMake.VehicleMake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_marca_vehiculo_nombre");

                    b.ToTable("marca_vehiculo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Vehiclemodel.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("marca_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<short?>("YearFrom")
                        .HasColumnType("smallint")
                        .HasColumnName("anio_desde");

                    b.Property<short?>("YearTo")
                        .HasColumnType("smallint")
                        .HasColumnName("anio_hasta");

                    b.Property<Guid?>("marca_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("marca_id");

                    b.ToTable("modelo_vehiculo", null, t =>
                        {
                            t.Property("marca_id")
                                .HasColumnName("marca_id1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Warranty.Warranty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Condiciones")
                        .HasColumnType("text")
                        .HasColumnName("condiciones");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<Guid>("MechanicId")
                        .HasColumnType("uuid")
                        .HasColumnName("mecanico_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("orden_id");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_servicio_id");

                    b.HasKey("Id");

                    b.HasIndex("MechanicId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_garantia_orden");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("garantia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Appointment.Appointment", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReceptionistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ServiceType.ServiceType", null)
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Vehicle.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Audit.Audit", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Citys.City", b =>
                {
                    b.HasOne("Domain.Entities.Departments.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.CustomerAddresses.CustomerAddress", b =>
                {
                    b.HasOne("Domain.Entities.Citys.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.CustomerEmails.CustomerEmail", b =>
                {
                    b.HasOne("Domain.Entities.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.CustomerPhones.CustomerPhone", b =>
                {
                    b.HasOne("Domain.Entities.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Departments.Department", b =>
                {
                    b.HasOne("Domain.Entities.Countries.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.InventoryLog.InventoryLog", b =>
                {
                    b.HasOne("Domain.Entities.OrderService.OrderService", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Purchase.Purchase", null)
                        .WithMany()
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.SparePart.SparePart", null)
                        .WithMany()
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Invoice.Invoice", b =>
                {
                    b.HasOne("Domain.Entities.OrderService.OrderService", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.InvoiceStatus.InvoiceStatus", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.MechanicTask.MechanicTask", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("mecanico_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.OrderService.OrderService", null)
                        .WithMany()
                        .HasForeignKey("orden_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.ServiceType.ServiceType", null)
                        .WithMany()
                        .HasForeignKey("tipo_servicio_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.MileageHistory.MileageHistory", b =>
                {
                    b.HasOne("Domain.Entities.Vehicle.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("vehiculo_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.OrderDetail.OrderDetail", b =>
                {
                    b.HasOne("Domain.Entities.OrderService.OrderService", null)
                        .WithMany()
                        .HasForeignKey("orden_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.SparePart.SparePart", null)
                        .WithMany()
                        .HasForeignKey("repuesto_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.OrderMechanic.OrderMechanic", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("mecanico_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.OrderService.OrderService", null)
                        .WithMany()
                        .HasForeignKey("orden_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Entities.OrderNote.OrderNote", b =>
                {
                    b.HasOne("Domain.Entities.OrderService.OrderService", null)
                        .WithMany()
                        .HasForeignKey("orden_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("usuario_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.OrderService.OrderService", b =>
                {
                    b.HasOne("Domain.Entities.Appointment.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.OrderStatus.OrderStatus", null)
                        .WithMany()
                        .HasForeignKey("estado_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("recepcionista_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Vehicle.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("vehiculo_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.OrderServiceType.OrderServiceType", b =>
                {
                    b.HasOne("Domain.Entities.OrderService.OrderService", null)
                        .WithMany()
                        .HasForeignKey("orden_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.ServiceType.ServiceType", null)
                        .WithMany()
                        .HasForeignKey("tipo_servicio_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.OrderStatusHistory.OrderStatusHistory", b =>
                {
                    b.HasOne("Domain.Entities.OrderStatus.OrderStatus", null)
                        .WithMany()
                        .HasForeignKey("estado_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.OrderService.OrderService", null)
                        .WithMany()
                        .HasForeignKey("orden_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("usuario_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.Payment.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Invoice.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PaymentMethod.PaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Purchase.Purchase", b =>
                {
                    b.HasOne("Domain.Entities.Supplier.Supplier", null)
                        .WithMany()
                        .HasForeignKey("proveedor_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("usuario_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.PurchaseDetail.PurchaseDetail", b =>
                {
                    b.HasOne("Domain.Entities.Purchase.Purchase", null)
                        .WithMany()
                        .HasForeignKey("compra_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.SparePart.SparePart", null)
                        .WithMany()
                        .HasForeignKey("repuesto_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.SparePart.SparePart", b =>
                {
                    b.HasOne("Domain.Entities.SpareCategory.SpareCategory", null)
                        .WithMany()
                        .HasForeignKey("categoria_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.UnitMeasure.UnitMeasure", null)
                        .WithMany()
                        .HasForeignKey("unidad_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.SparePartSupplier.SparePartSupplier", b =>
                {
                    b.HasOne("Domain.Entities.Supplier.Supplier", null)
                        .WithMany()
                        .HasForeignKey("proveedor_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.SparePart.SparePart", null)
                        .WithMany()
                        .HasForeignKey("repuesto_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.Supplier.Supplier", b =>
                {
                    b.HasOne("Domain.Entities.Citys.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proveedor_ciudad");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.HasOne("Domain.Entities.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("rol_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.Vehicle.Vehicle", b =>
                {
                    b.HasOne("Domain.Entities.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Vehiclemodel.VehicleModel", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Vehiclemodel.VehicleModel", b =>
                {
                    b.HasOne("Domain.Entities.VehicleMake.VehicleMake", null)
                        .WithMany()
                        .HasForeignKey("marca_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.Warranty.Warranty", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.OrderService.OrderService", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ServiceType.ServiceType", null)
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
